auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: summer insect cannot comprehend ice or snow.
url: http://youbinhong.github.io
feed: /atom.xml
author_info: <a href="http://youbinhong.github.io/">youbinhong</a>